apiVersion: v1
kind: Service
metadata:
  name: seedtag-text-classifier-service
spec:
  selector:
    app: seedtag-text-classifier
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer